# Eingabe der Zimmer Eigenschaften
zimmer_name = input("Gib den Namen des Zimmers ein: ")
groesse = int(input("Gib die Größe des Zimmers in Quadratmetern ein: "))
anzahl_fenster = int(input("Gib die Anzahl der Fenster ein: "))
bodenart = input("Gib die Bodenart ein: ")
farbe_wand = input("Gib die Wandfarbe ein: ")
moebel = input("Gib die Art der Möbel ein: ")
lichtquelle = input("Gib die Lichtquelle ein: ")
heizung = input("Gib die Heizungsart ein: ")
decke_hoehe = int(input("Gib die Deckenhöhe in Metern ein: "))
besonderheiten = input("Gib besondere Eigenschaften des Zimmers ein: ")

# Daten ausgeben
print("Hier sind die eingegebenen Eigenschaften des Zimmers:")
print("Name:", zimmer_name)
print("Größe:", groesse)
print("Anzahl der Fenster:", anzahl_fenster)
print("Bodenart:", bodenart)
print("Wandfarbe:", farbe_wand)
print("Möbel:", moebel)
print("Lichtquelle:", lichtquelle)
print("Heizung:", heizung)
print("Deckenhöhe:", decke_hoehe)
print("Besonderheiten:", besonderheiten)